const cacheName = 'entireApp';

const cacheAssets = [
    "/",
    '/index.html',
    '/css/treeView.css',
    '/js/main.js',
    '/resources/',
    '/resources/DQMJ2_InComon/',
    '/resources/DQMJ2_InComon/images/',
    'resources/DQMJ2/',
    'resources/DQMJ2_Pro/',
    // DQMJ2
    "/resources/DQMJ2/IDToMonster.jjson",
    "/resources/DQMJ2/monster_list.jjson",
    "/resources/DQMJ2/monsterToID.jjson",
    "/resources/DQMJ2/synth.json",
    // DQMJ2_Pro
    "/resources/DQMJ2_Pro/IDToMonster.json",
    "/resources/DQMJ2_Pro/monster_list.json",
    "/resources/DQMJ2_Pro/monsterToID.json",
    "/resources/DQMJ2_Pro/synth.json",
    // In Common
    '/resources/DQMJ2_InComon/synthProp.json',
    '/resources/DQMJ2_InComon/monstList.json',
    // the images
    "/resources/DQMJ2_InComon/images/aamon.png",
    "/resources/DQMJ2_InComon/images/abyss diver.png",
    "/resources/DQMJ2_InComon/images/ace of spades.png",
    "/resources/DQMJ2_InComon/images/aggrosculpture.png",
    "/resources/DQMJ2_InComon/images/alabast dragon.png",
    "/resources/DQMJ2_InComon/images/anchorman.png",
    "/resources/DQMJ2_InComon/images/angel slime.png",
    "/resources/DQMJ2_InComon/images/aquarion.png",
    "/resources/DQMJ2_InComon/images/aquestrian gladiator.png",
    "/resources/DQMJ2_InComon/images/archdemon.png",
    "/resources/DQMJ2_InComon/images/argon lizard.png",
    "/resources/DQMJ2_InComon/images/armorpede.png",
    "/resources/DQMJ2_InComon/images/armoured wartoise.png",
    "/resources/DQMJ2_InComon/images/armyant.png",
    "/resources/DQMJ2_InComon/images/atlas.png",
    "/resources/DQMJ2_InComon/images/baalzack.png",
    "/resources/DQMJ2_InComon/images/baby bjorn.png",
    "/resources/DQMJ2_InComon/images/bad egg.png",
    "/resources/DQMJ2_InComon/images/bag o' laughs.png",
    "/resources/DQMJ2_InComon/images/balhib.png",
    "/resources/DQMJ2_InComon/images/bantamweight.png",
    "/resources/DQMJ2_InComon/images/baramos.png",
    "/resources/DQMJ2_InComon/images/barbarus.png",
    "/resources/DQMJ2_InComon/images/barracuda.png",
    "/resources/DQMJ2_InComon/images/battering ram.png",
    "/resources/DQMJ2_InComon/images/beast family.png",
    "/resources/DQMJ2_InComon/images/beetleboy.png",
    "/resources/DQMJ2_InComon/images/beetlebully.png",
    "/resources/DQMJ2_InComon/images/behemoth slime.png",
    "/resources/DQMJ2_InComon/images/belial.png",
    "/resources/DQMJ2_InComon/images/beshemoth slime.png",
    "/resources/DQMJ2_InComon/images/bewarewolf.png",
    "/resources/DQMJ2_InComon/images/bilhaw.png",
    "/resources/DQMJ2_InComon/images/bishop ladja.png",
    "/resources/DQMJ2_InComon/images/bjorn.png",
    "/resources/DQMJ2_InComon/images/black dragon.png",
    "/resources/DQMJ2_InComon/images/blackmar.png",
    "/resources/DQMJ2_InComon/images/blizzybody.png",
    "/resources/DQMJ2_InComon/images/bodkin archer.png",
    "/resources/DQMJ2_InComon/images/boe.png",
    "/resources/DQMJ2_InComon/images/boh.png",
    "/resources/DQMJ2_InComon/images/bona constrictor.png",
    "/resources/DQMJ2_InComon/images/bone baron.png",
    "/resources/DQMJ2_InComon/images/boppin' badger.png",
    "/resources/DQMJ2_InComon/images/boreal serpent.png",
    "/resources/DQMJ2_InComon/images/boring bug.png",
    "/resources/DQMJ2_InComon/images/boss troll.png",
    "/resources/DQMJ2_InComon/images/brownie.png",
    "/resources/DQMJ2_InComon/images/bubble slime.png",
    "/resources/DQMJ2_InComon/images/buffalogre.png",
    "/resources/DQMJ2_InComon/images/bullfinch.png",
    "/resources/DQMJ2_InComon/images/butchoman.png",
    "/resources/DQMJ2_InComon/images/cactiball.png",
    "/resources/DQMJ2_InComon/images/cannibox.png",
    "/resources/DQMJ2_InComon/images/canzar.png",
    "/resources/DQMJ2_InComon/images/capsichum.png",
    "/resources/DQMJ2_InComon/images/captain crow.png",
    "/resources/DQMJ2_InComon/images/catfly.png",
    "/resources/DQMJ2_InComon/images/cerberus.png",
    "/resources/DQMJ2_InComon/images/chainine.png",
    "/resources/DQMJ2_InComon/images/chargon.png",
    "/resources/DQMJ2_InComon/images/chariot chappie.png",
    "/resources/DQMJ2_InComon/images/cheeky tiki.png",
    "/resources/DQMJ2_InComon/images/chimaera x.png",
    "/resources/DQMJ2_InComon/images/chimaera xy.png",
    "/resources/DQMJ2_InComon/images/chimaera.png",
    "/resources/DQMJ2_InComon/images/claynite.png",
    "/resources/DQMJ2_InComon/images/cluboon ace.png",
    "/resources/DQMJ2_InComon/images/cluboon.png",
    "/resources/DQMJ2_InComon/images/cobra cardinal.png",
    "/resources/DQMJ2_InComon/images/cockateer.png",
    "/resources/DQMJ2_InComon/images/conkettes.png",
    "/resources/DQMJ2_InComon/images/conklave x.png",
    "/resources/DQMJ2_InComon/images/conklave xy.png",
    "/resources/DQMJ2_InComon/images/conklave.png",
    "/resources/DQMJ2_InComon/images/corrupt carter.png",
    "/resources/DQMJ2_InComon/images/corvus.png",
    "/resources/DQMJ2_InComon/images/crabid.png",
    "/resources/DQMJ2_InComon/images/cragdevil.png",
    "/resources/DQMJ2_InComon/images/cross bones.png",
    "/resources/DQMJ2_InComon/images/cross eye.png",
    "/resources/DQMJ2_InComon/images/cruelcumber.png",
    "/resources/DQMJ2_InComon/images/cumulus rex.png",
    "/resources/DQMJ2_InComon/images/cureslime.png",
    "/resources/DQMJ2_InComon/images/cyber slime.png",
    "/resources/DQMJ2_InComon/images/damselfly.png",
    "/resources/DQMJ2_InComon/images/dancing devil.png",
    "/resources/DQMJ2_InComon/images/dancing flame.png",
    "/resources/DQMJ2_InComon/images/dangler fish.png",
    "/resources/DQMJ2_InComon/images/darck.png",
    "/resources/DQMJ2_InComon/images/dark slime knight.png",
    "/resources/DQMJ2_InComon/images/dark slime.png",
    "/resources/DQMJ2_InComon/images/darkcrab.png",
    "/resources/DQMJ2_InComon/images/darkonium slime.png",
    "/resources/DQMJ2_InComon/images/demighoul.png",
    "/resources/DQMJ2_InComon/images/demon family.png",
    "/resources/DQMJ2_InComon/images/demon king.png",
    "/resources/DQMJ2_InComon/images/demon-at-arms.png",
    "/resources/DQMJ2_InComon/images/demonrider.png",
    "/resources/DQMJ2_InComon/images/dessert demon.png",
    "/resources/DQMJ2_InComon/images/dhoulmagus.png",
    "/resources/DQMJ2_InComon/images/dhuran.png",
    "/resources/DQMJ2_InComon/images/diamagon ace.png",
    "/resources/DQMJ2_InComon/images/diamagon.png",
    "/resources/DQMJ2_InComon/images/diamond slime.png",
    "/resources/DQMJ2_InComon/images/diemon.png",
    "/resources/DQMJ2_InComon/images/dierantula.png",
    "/resources/DQMJ2_InComon/images/dimensional dragon.png",
    "/resources/DQMJ2_InComon/images/dingaling.png",
    "/resources/DQMJ2_InComon/images/don mole.png",
    "/resources/DQMJ2_InComon/images/dorsal fiend.png",
    "/resources/DQMJ2_InComon/images/dr snapped.png",
    "/resources/DQMJ2_InComon/images/dracky.png",
    "/resources/DQMJ2_InComon/images/dracolord.png",
    "/resources/DQMJ2_InComon/images/drag goof.png",
    "/resources/DQMJ2_InComon/images/dragon family.png",
    "/resources/DQMJ2_InComon/images/dragon rider.png",
    "/resources/DQMJ2_InComon/images/dragon slime.png",
    "/resources/DQMJ2_InComon/images/dragonlord.png",
    "/resources/DQMJ2_InComon/images/dragonthorn.png",
    "/resources/DQMJ2_InComon/images/dragovian lord.png",
    "/resources/DQMJ2_InComon/images/dragurn.png",
    "/resources/DQMJ2_InComon/images/drake slime.png",
    "/resources/DQMJ2_InComon/images/drakorpse.png",
    "/resources/DQMJ2_InComon/images/drakulard.png",
    "/resources/DQMJ2_InComon/images/drakularge.png",
    "/resources/DQMJ2_InComon/images/drohl diabolist.png",
    "/resources/DQMJ2_InComon/images/drohl drone.png",
    "/resources/DQMJ2_InComon/images/dual duellers.png",
    "/resources/DQMJ2_InComon/images/dullahan.png",
    "/resources/DQMJ2_InComon/images/elder pipit.png",
    "/resources/DQMJ2_InComon/images/empyrea.png",
    "/resources/DQMJ2_InComon/images/erazor blade.png",
    "/resources/DQMJ2_InComon/images/estark.png",
    "/resources/DQMJ2_InComon/images/ethereal serpent.png",
    "/resources/DQMJ2_InComon/images/eveel.png",
    "/resources/DQMJ2_InComon/images/evil beast.png",
    "/resources/DQMJ2_InComon/images/exorsus.png",
    "/resources/DQMJ2_InComon/images/eyevory tusk-tusk.png",
    "/resources/DQMJ2_InComon/images/fallen priest.png",
    "/resources/DQMJ2_InComon/images/fencing fox.png",
    "/resources/DQMJ2_InComon/images/firebird.png",
    "/resources/DQMJ2_InComon/images/firespirit.png",
    "/resources/DQMJ2_InComon/images/firn fiend.png",
    "/resources/DQMJ2_InComon/images/flamethrower.png",
    "/resources/DQMJ2_InComon/images/florajay.png",
    "/resources/DQMJ2_InComon/images/fluffy.png",
    "/resources/DQMJ2_InComon/images/flyguy.png",
    "/resources/DQMJ2_InComon/images/foo dog.png",
    "/resources/DQMJ2_InComon/images/fright knight.png",
    "/resources/DQMJ2_InComon/images/frogface.png",
    "/resources/DQMJ2_InComon/images/frostburn.png",
    "/resources/DQMJ2_InComon/images/frou-frou.png",
    "/resources/DQMJ2_InComon/images/frou-fry.png",
    "/resources/DQMJ2_InComon/images/funghoul.png",
    "/resources/DQMJ2_InComon/images/gadis.png",
    "/resources/DQMJ2_InComon/images/gamadius.png",
    "/resources/DQMJ2_InComon/images/gargoyle.png",
    "/resources/DQMJ2_InComon/images/garuda.png",
    "/resources/DQMJ2_InComon/images/gasbagon.png",
    "/resources/DQMJ2_InComon/images/gem slime.png",
    "/resources/DQMJ2_InComon/images/gemon.png",
    "/resources/DQMJ2_InComon/images/general.png",
    "/resources/DQMJ2_InComon/images/genie sanguini.png",
    "/resources/DQMJ2_InComon/images/ghost.png",
    "/resources/DQMJ2_InComon/images/giant moth.png",
    "/resources/DQMJ2_InComon/images/gigamute.png",
    "/resources/DQMJ2_InComon/images/gigantes.png",
    "/resources/DQMJ2_InComon/images/gold golem.png",
    "/resources/DQMJ2_InComon/images/golem.png",
    "/resources/DQMJ2_InComon/images/goodybag x.png",
    "/resources/DQMJ2_InComon/images/goodybag xy.png",
    "/resources/DQMJ2_InComon/images/goodybag.png",
    "/resources/DQMJ2_InComon/images/goreham-hogg.png",
    "/resources/DQMJ2_InComon/images/gorerilla.png",
    "/resources/DQMJ2_InComon/images/goresby-purrvis.png",
    "/resources/DQMJ2_InComon/images/gracos.png",
    "/resources/DQMJ2_InComon/images/grandpa slime.png",
    "/resources/DQMJ2_InComon/images/great argon lizard.png",
    "/resources/DQMJ2_InComon/images/great dracky.png",
    "/resources/DQMJ2_InComon/images/great dragon.png",
    "/resources/DQMJ2_InComon/images/great godbird.png",
    "/resources/DQMJ2_InComon/images/great sabrecat.png",
    "/resources/DQMJ2_InComon/images/great sabrecub.png",
    "/resources/DQMJ2_InComon/images/green dragon x.png",
    "/resources/DQMJ2_InComon/images/green dragon xy.png",
    "/resources/DQMJ2_InComon/images/green dragon.png",
    "/resources/DQMJ2_InComon/images/greygnarl.png",
    "/resources/DQMJ2_InComon/images/grim keeper.png",
    "/resources/DQMJ2_InComon/images/grim rider.png",
    "/resources/DQMJ2_InComon/images/gripevine.png",
    "/resources/DQMJ2_InComon/images/gruffon.png",
    "/resources/DQMJ2_InComon/images/gryphon.png",
    "/resources/DQMJ2_InComon/images/hacksaurus.png",
    "/resources/DQMJ2_InComon/images/hades condor.png",
    "/resources/DQMJ2_InComon/images/hammerhood.png",
    "/resources/DQMJ2_InComon/images/hargon.png",
    "/resources/DQMJ2_InComon/images/harmour.png",
    "/resources/DQMJ2_InComon/images/hawkhart ace.png",
    "/resources/DQMJ2_InComon/images/hawkhart.png",
    "/resources/DQMJ2_InComon/images/headhunter.png",
    "/resources/DQMJ2_InComon/images/healslime.png",
    "/resources/DQMJ2_InComon/images/heedoovoodoo.png",
    "/resources/DQMJ2_InComon/images/heligator.png",
    "/resources/DQMJ2_InComon/images/hell hornet.png",
    "/resources/DQMJ2_InComon/images/hellhound.png",
    "/resources/DQMJ2_InComon/images/heyedra.png",
    "/resources/DQMJ2_InComon/images/high djinks.png",
    "/resources/DQMJ2_InComon/images/hootingham gore.png",
    "/resources/DQMJ2_InComon/images/hunter mech.png",
    "/resources/DQMJ2_InComon/images/hyper heyedra.png",
    "/resources/DQMJ2_InComon/images/hyperanemon.png",
    "/resources/DQMJ2_InComon/images/imp.png",
    "/resources/DQMJ2_InComon/images/incarni family.png",
    "/resources/DQMJ2_InComon/images/inopp.png",
    "/resources/DQMJ2_InComon/images/jailcat.png",
    "/resources/DQMJ2_InComon/images/jamirus.png",
    "/resources/DQMJ2_InComon/images/jargon.png",
    "/resources/DQMJ2_InComon/images/juggular.png",
    "/resources/DQMJ2_InComon/images/jum.png",
    "/resources/DQMJ2_InComon/images/jumping jackal.png",
    "/resources/DQMJ2_InComon/images/kap.png",
    "/resources/DQMJ2_InComon/images/khalamari kid.png",
    "/resources/DQMJ2_InComon/images/khalamari.png",
    "/resources/DQMJ2_InComon/images/killer ape.png",
    "/resources/DQMJ2_InComon/images/killerpillar.png",
    "/resources/DQMJ2_InComon/images/killing machine.png",
    "/resources/DQMJ2_InComon/images/king bubble slime.png",
    "/resources/DQMJ2_InComon/images/king cureslime.png",
    "/resources/DQMJ2_InComon/images/king godwyn.png",
    "/resources/DQMJ2_InComon/images/king kelp.png",
    "/resources/DQMJ2_InComon/images/king korol.png",
    "/resources/DQMJ2_InComon/images/king slime.png",
    "/resources/DQMJ2_InComon/images/king squid.png",
    "/resources/DQMJ2_InComon/images/kingy.png",
    "/resources/DQMJ2_InComon/images/komodo.png",
    "/resources/DQMJ2_InComon/images/kon.png",
    "/resources/DQMJ2_InComon/images/leokid.png",
    "/resources/DQMJ2_InComon/images/leonyx.png",
    "/resources/DQMJ2_InComon/images/leopold.png",
    "/resources/DQMJ2_InComon/images/lesser demon.png",
    "/resources/DQMJ2_InComon/images/lethal armour.png",
    "/resources/DQMJ2_InComon/images/leviathan.png",
    "/resources/DQMJ2_InComon/images/lips.png",
    "/resources/DQMJ2_InComon/images/liquid metal king slime.png",
    "/resources/DQMJ2_InComon/images/liquid metal slime.png",
    "/resources/DQMJ2_InComon/images/living statue.png",
    "/resources/DQMJ2_InComon/images/lizardfly.png",
    "/resources/DQMJ2_InComon/images/lleviathan.png",
    "/resources/DQMJ2_InComon/images/lump wizard.png",
    "/resources/DQMJ2_InComon/images/mad knight.png",
    "/resources/DQMJ2_InComon/images/magarugi.png",
    "/resources/DQMJ2_InComon/images/magic slime.png",
    "/resources/DQMJ2_InComon/images/magmalice.png",
    "/resources/DQMJ2_InComon/images/malevolamp.png",
    "/resources/DQMJ2_InComon/images/malevolynx.png",
    "/resources/DQMJ2_InComon/images/malroth.png",
    "/resources/DQMJ2_InComon/images/mandrake marshal.png",
    "/resources/DQMJ2_InComon/images/maniacal mole.png",
    "/resources/DQMJ2_InComon/images/marquis de leon.png",
    "/resources/DQMJ2_InComon/images/material family.png",
    "/resources/DQMJ2_InComon/images/mecha-mynah.png",
    "/resources/DQMJ2_InComon/images/mechanowyrm.png",
    "/resources/DQMJ2_InComon/images/meddle slime.png",
    "/resources/DQMJ2_InComon/images/megalodon.png",
    "/resources/DQMJ2_InComon/images/mental pitcher.png",
    "/resources/DQMJ2_InComon/images/merman.png",
    "/resources/DQMJ2_InComon/images/metal dragon.png",
    "/resources/DQMJ2_InComon/images/metal kaiser slime.png",
    "/resources/DQMJ2_InComon/images/metal king slime.png",
    "/resources/DQMJ2_InComon/images/metal slime knight.png",
    "/resources/DQMJ2_InComon/images/metal slime.png",
    "/resources/DQMJ2_InComon/images/mimic.png",
    "/resources/DQMJ2_InComon/images/mischievous mole.png",
    "/resources/DQMJ2_InComon/images/missing lynx.png",
    "/resources/DQMJ2_InComon/images/moai minstrel.png",
    "/resources/DQMJ2_InComon/images/mohawker.png",
    "/resources/DQMJ2_InComon/images/monkey zombie.png",
    "/resources/DQMJ2_InComon/images/moosifer.png",
    "/resources/DQMJ2_InComon/images/mortamor.png",
    "/resources/DQMJ2_InComon/images/mortella.png",
    "/resources/DQMJ2_InComon/images/mortoad.png",
    "/resources/DQMJ2_InComon/images/mottle slime.png",
    "/resources/DQMJ2_InComon/images/mud mannequin.png",
    "/resources/DQMJ2_InComon/images/muddy hand.png",
    "/resources/DQMJ2_InComon/images/mum.png",
    "/resources/DQMJ2_InComon/images/mumboh-jumboe.png",
    "/resources/DQMJ2_InComon/images/mummy boy.png",
    "/resources/DQMJ2_InComon/images/munchie.png",
    "/resources/DQMJ2_InComon/images/murdaw.png",
    "/resources/DQMJ2_InComon/images/nardragon.png",
    "/resources/DQMJ2_InComon/images/nature family.png",
    "/resources/DQMJ2_InComon/images/nemeslime.png",
    "/resources/DQMJ2_InComon/images/night clubber.png",
    "/resources/DQMJ2_InComon/images/night emperor.png",
    "/resources/DQMJ2_InComon/images/night knight.png",
    "/resources/DQMJ2_InComon/images/nimzo.png",
    "/resources/DQMJ2_InComon/images/noble gasbagon.png",
    "/resources/DQMJ2_InComon/images/nodoph.png",
    "/resources/DQMJ2_InComon/images/nokturnus.png",
    "/resources/DQMJ2_InComon/images/notso macho.png",
    "/resources/DQMJ2_InComon/images/numen.png",
    "/resources/DQMJ2_InComon/images/octagoon.png",
    "/resources/DQMJ2_InComon/images/octavian sentry.png",
    "/resources/DQMJ2_InComon/images/orc.png",
    "/resources/DQMJ2_InComon/images/orgodemir.png",
    "/resources/DQMJ2_InComon/images/orochi.png",
    "/resources/DQMJ2_InComon/images/overkilling machine.png",
    "/resources/DQMJ2_InComon/images/pan piper.png",
    "/resources/DQMJ2_InComon/images/panickle.png",
    "/resources/DQMJ2_InComon/images/paws.png",
    "/resources/DQMJ2_InComon/images/pazuzu.png",
    "/resources/DQMJ2_InComon/images/phantom fencer.png",
    "/resources/DQMJ2_InComon/images/phantom swordsman.png",
    "/resources/DQMJ2_InComon/images/pickeerer.png",
    "/resources/DQMJ2_InComon/images/pink sanguini.png",
    "/resources/DQMJ2_InComon/images/pipit.png",
    "/resources/DQMJ2_InComon/images/platypunk.png",
    "/resources/DQMJ2_InComon/images/pocus poppet.png",
    "/resources/DQMJ2_InComon/images/pompom bomb.png",
    "/resources/DQMJ2_InComon/images/powie yowie.png",
    "/resources/DQMJ2_InComon/images/prickly prankster.png",
    "/resources/DQMJ2_InComon/images/prince o' thieves.png",
    "/resources/DQMJ2_InComon/images/prism peacock.png",
    "/resources/DQMJ2_InComon/images/protomech.png",
    "/resources/DQMJ2_InComon/images/pruslas.png",
    "/resources/DQMJ2_InComon/images/psaro.png",
    "/resources/DQMJ2_InComon/images/puppeteer.png",
    "/resources/DQMJ2_InComon/images/ragin' contagion.png",
    "/resources/DQMJ2_InComon/images/rashaverak.png",
    "/resources/DQMJ2_InComon/images/red dragon.png",
    "/resources/DQMJ2_InComon/images/restless armour.png",
    "/resources/DQMJ2_InComon/images/rhapthorne 2.png",
    "/resources/DQMJ2_InComon/images/rhapthorne.png",
    "/resources/DQMJ2_InComon/images/rigor mortex.png",
    "/resources/DQMJ2_InComon/images/riptide.png",
    "/resources/DQMJ2_InComon/images/robbin' hood.png",
    "/resources/DQMJ2_InComon/images/robbin' huddle.png",
    "/resources/DQMJ2_InComon/images/robo slime.png",
    "/resources/DQMJ2_InComon/images/rockbomb.png",
    "/resources/DQMJ2_InComon/images/roseguardin.png",
    "/resources/DQMJ2_InComon/images/rotten egg.png",
    "/resources/DQMJ2_InComon/images/rubble slime.png",
    "/resources/DQMJ2_InComon/images/ruin.png",
    "/resources/DQMJ2_InComon/images/sagittar.png",
    "/resources/DQMJ2_InComon/images/satyr.png",
    "/resources/DQMJ2_InComon/images/schleiman tank.png",
    "/resources/DQMJ2_InComon/images/schwarzman tank.png",
    "/resources/DQMJ2_InComon/images/schwarzman.png",
    "/resources/DQMJ2_InComon/images/scissor beatle.png",
    "/resources/DQMJ2_InComon/images/scorpion.png",
    "/resources/DQMJ2_InComon/images/scytheborg.png",
    "/resources/DQMJ2_InComon/images/sea dragon.png",
    "/resources/DQMJ2_InComon/images/seadog.png",
    "/resources/DQMJ2_InComon/images/seasaur.png",
    "/resources/DQMJ2_InComon/images/see urchin.png",
    "/resources/DQMJ2_InComon/images/seedy weedie.png",
    "/resources/DQMJ2_InComon/images/shadow.png",
    "/resources/DQMJ2_InComon/images/she-slime.png",
    "/resources/DQMJ2_InComon/images/shell slime.png",
    "/resources/DQMJ2_InComon/images/shield ogre.png",
    "/resources/DQMJ2_InComon/images/shogum.png",
    "/resources/DQMJ2_InComon/images/silvapithecus.png",
    "/resources/DQMJ2_InComon/images/sintaur.png",
    "/resources/DQMJ2_InComon/images/sitting lion beast.png",
    "/resources/DQMJ2_InComon/images/skelegon.png",
    "/resources/DQMJ2_InComon/images/skeleton soldier.png",
    "/resources/DQMJ2_InComon/images/skeleton x.png",
    "/resources/DQMJ2_InComon/images/skeleton xy.png",
    "/resources/DQMJ2_InComon/images/skeleton.png",
    "/resources/DQMJ2_InComon/images/skipper.png",
    "/resources/DQMJ2_InComon/images/slider girl.png",
    "/resources/DQMJ2_InComon/images/slime blaster.png",
    "/resources/DQMJ2_InComon/images/slime family.png",
    "/resources/DQMJ2_InComon/images/slime gang.png",
    "/resources/DQMJ2_InComon/images/slime knight.png",
    "/resources/DQMJ2_InComon/images/slime stack.png",
    "/resources/DQMJ2_InComon/images/slime x.png",
    "/resources/DQMJ2_InComon/images/slime xy.png",
    "/resources/DQMJ2_InComon/images/slime.png",
    "/resources/DQMJ2_InComon/images/slon.png",
    "/resources/DQMJ2_InComon/images/small fry.png",
    "/resources/DQMJ2_InComon/images/snail slime.png",
    "/resources/DQMJ2_InComon/images/snapdragon.png",
    "/resources/DQMJ2_InComon/images/snowbird.png",
    "/resources/DQMJ2_InComon/images/snowmangler.png",
    "/resources/DQMJ2_InComon/images/soulspawn.png",
    "/resources/DQMJ2_InComon/images/spiked hare.png",
    "/resources/DQMJ2_InComon/images/spitnik.png",
    "/resources/DQMJ2_InComon/images/spotking.png",
    "/resources/DQMJ2_InComon/images/squign.png",
    "/resources/DQMJ2_InComon/images/stark raven.png",
    "/resources/DQMJ2_InComon/images/stella.png",
    "/resources/DQMJ2_InComon/images/stormsgate citadel.png",
    "/resources/DQMJ2_InComon/images/stump chump.png",
    "/resources/DQMJ2_InComon/images/swarmtroop.png",
    "/resources/DQMJ2_InComon/images/swingin' hipster.png",
    "/resources/DQMJ2_InComon/images/tall tail.png",
    "/resources/DQMJ2_InComon/images/tantamount.png",
    "/resources/DQMJ2_InComon/images/taurus.png",
    "/resources/DQMJ2_InComon/images/teeny sanguini x.png",
    "/resources/DQMJ2_InComon/images/teeny sanguini xy.png",
    "/resources/DQMJ2_InComon/images/teeny sanguini.png",
    "/resources/DQMJ2_InComon/images/tentickle.png",
    "/resources/DQMJ2_InComon/images/thornella.png",
    "/resources/DQMJ2_InComon/images/ticking timeburrm.png",
    "/resources/DQMJ2_InComon/images/time sage.png",
    "/resources/DQMJ2_InComon/images/titanis.png",
    "/resources/DQMJ2_InComon/images/torai wanda.png",
    "/resources/DQMJ2_InComon/images/tortoceratops.png",
    "/resources/DQMJ2_InComon/images/tortured soul.png",
    "/resources/DQMJ2_InComon/images/trap box.png",
    "/resources/DQMJ2_InComon/images/trauminator.png",
    "/resources/DQMJ2_InComon/images/tree feller.png",
    "/resources/DQMJ2_InComon/images/treeface.png",
    "/resources/DQMJ2_InComon/images/trigertaur.png",
    "/resources/DQMJ2_InComon/images/trode.png",
    "/resources/DQMJ2_InComon/images/tyrannosaurus wrecks.png",
    "/resources/DQMJ2_InComon/images/tyrantosaurus.png",
    "/resources/DQMJ2_InComon/images/uberkilling machine.png",
    "/resources/DQMJ2_InComon/images/ultra slime.png",
    "/resources/DQMJ2_InComon/images/undead family.png",
    "/resources/DQMJ2_InComon/images/wailin' weed.png",
    "/resources/DQMJ2_InComon/images/walking corpse.png",
    "/resources/DQMJ2_InComon/images/warubou.png",
    "/resources/DQMJ2_InComon/images/wax murderer.png",
    "/resources/DQMJ2_InComon/images/weaken beakon.png",
    "/resources/DQMJ2_InComon/images/weartiger.png",
    "/resources/DQMJ2_InComon/images/weedie.png",
    "/resources/DQMJ2_InComon/images/wight king.png",
    "/resources/DQMJ2_InComon/images/wight knight.png",
    "/resources/DQMJ2_InComon/images/wild boarfish.png",
    "/resources/DQMJ2_InComon/images/wild slime.png",
    "/resources/DQMJ2_InComon/images/wildcard.png",
    "/resources/DQMJ2_InComon/images/winky.png",
    "/resources/DQMJ2_InComon/images/wishmaster.png",
    "/resources/DQMJ2_InComon/images/wooper trooper.png",
    "/resources/DQMJ2_InComon/images/wormonger (2).png",
    "/resources/DQMJ2_InComon/images/wormonger.png",
    "/resources/DQMJ2_InComon/images/wrecktor.png",
    "/resources/DQMJ2_InComon/images/wulfspade ace.png",
    "/resources/DQMJ2_InComon/images/wulfspade.png",
    "/resources/DQMJ2_InComon/images/x47.png",
    "/resources/DQMJ2_InComon/images/xenlon.png",
    "/resources/DQMJ2_InComon/images/xiphos.png",
    "/resources/DQMJ2_InComon/images/yabby.png",
    "/resources/DQMJ2_InComon/images/yggdrasil.png",
    "/resources/DQMJ2_InComon/images/zenith dragon.png",
    "/resources/DQMJ2_InComon/images/zoma.png",
    "/resources/DQMJ2_InComon/images/zoma's devil.png",
]
const addResourcesToCache = async (resources) => {
    const cache = await caches.open("entireApp");
    await cache.addAll(resources);
};
  
self.addEventListener("install", (event) => {
    event.waitUntil(
        addResourcesToCache(cacheAssets),
    );
});
async function cacheThenNetwork(request) {
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
        console.log("Found response in cache:", cachedResponse);
        return cachedResponse;
    }
    console.log("Falling back to network");
    return fetch(request);
}
  
self.addEventListener("fetch", (event) => {
    console.log(`Handling fetch event for ${event.request.url}`);
    event.respondWith(cacheThenNetwork(event.request));
});
  